services:
  - type: web
    name: aura-carbon-tracker
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python database.py init
      sudo apt-get update
      sudo apt-get install -y tesseract-ocr libtesseract-dev
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        value: your_groq_api_key_here
      - key: GOOGLE_OAUTH_CLIENT_ID
        value: your_google_client_id
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        value: your_google_client_secret
      - key: DATABASE_URL
        fromDatabase:
          name: aura-db
          property: connectionString
